const BASE_URL = "https://norma.nomoreparties.space/api";
const WS_BASE_URL = "wss://norma.nomoreparties.space/orders";

const BUN = "bun";
const SAUCE = "sauce";
const FILLING = "filling";

export const PROFILE_PAGE_TEXT =
  "В этом разделе вы можете изменить свои персональные данные";
export const ORDER_PAGE_TEXT =
  "В этом разделе содержится информация о ваших заказах";

const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
const GET_INGREDIENTS_SUCCES: "GET_INGREDIENTS_SUCCES" = "GET_INGREDIENTS_SUCCES";
const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";
const SET_INGREDIENTS: "SET_INGREDIENTS" = "SET_INGREDIENTS";
const ADD_INGREDIENTS: "ADD_INGREDIENTS" = "ADD_INGREDIENTS";
const REMOVE_INGREDIENTS: "REMOVE_INGREDIENTS" = "REMOVE_INGREDIENTS";
const REMOVE_ALL_INGREDIENTS: "REMOVE_ALL_INGREDIENTS" = "REMOVE_ALL_INGREDIENTS";
const REPLASE_INGREDIENT: "REPLASE_INGREDIENT" = "REPLASE_INGREDIENT";
const SET_ORDER: "SET_ORDER" = "SET_ORDER";
const SET_ORDER_SUCCES: "SET_ORDER_SUCCES" = "SET_ORDER_SUCCES";
const SET_ORDER_FAILED: "SET_ORDER_SUCCES" = "SET_ORDER_SUCCES";
const SET_ORDER_REMOVE: "SET_ORDER_REMOVE" = "SET_ORDER_REMOVE";
const RESET: "RESET" = "RESET";
const ADD_USER: "ADD_USER" = "ADD_USER";
const ADD_USER_SUCCES: "ADD_USER_SUCCES" = "ADD_USER_SUCCES";
const ADD_USER_FAILED: "ADD_USER__FAILED" = "ADD_USER__FAILED";
const AUTH_CHECKED: "AUTH_CHECKED" = "AUTH_CHECKED";
const REMOVE_USER: "REMOVE_USER" = "REMOVE_USER";
const GET_USER: "GET_USER" = "GET_USER";
const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
const SET_USER: "SET_USER" = "SET_USER";
const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";
const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
const WS_CONNECTION_START_ALL_ORDERS: 'WS_CONNECTION_START_ALL_ORDERS' = 'WS_CONNECTION_START_ALL_ORDERS';
const WS_CONNECTION_START_USER_ORDERS: 'WS_CONNECTION_START_USER_ORDERS' = 'WS_CONNECTION_START_USER_ORDERS';
const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS'; 
const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';

export {
  BASE_URL,
  WS_BASE_URL,
  BUN,
  SAUCE,
  FILLING,
  GET_INGREDIENTS,
  GET_INGREDIENTS_SUCCES,
  GET_INGREDIENTS_FAILED,
  SET_INGREDIENTS,
  SET_ORDER_SUCCES,
  SET_ORDER_FAILED,
  SET_ORDER_REMOVE,
  ADD_INGREDIENTS,
  REMOVE_INGREDIENTS,
  REMOVE_ALL_INGREDIENTS,
  REPLASE_INGREDIENT,
  SET_ORDER,
  RESET,
  ADD_USER,
  ADD_USER_SUCCES,
  ADD_USER_FAILED,
  AUTH_CHECKED,
  REMOVE_USER,
  GET_USER,
  GET_USER_SUCCESS,
  GET_USER_FAILED,
  SET_USER,
  SET_USER_SUCCESS,
  SET_USER_FAILED,
  WS_CONNECTION_START,
  WS_CONNECTION_SUCCESS,
  WS_CONNECTION_ERROR,
  WS_CONNECTION_CLOSED,
  WS_GET_MESSAGE,
  WS_SEND_MESSAGE,
  WS_CONNECTION_START_ALL_ORDERS,
  WS_CONNECTION_START_USER_ORDERS
};

