const API_URL = "https://norma.nomoreparties.space/api";

const BUN = "bun";
const SAUCE = "sauce";
const FILLING = "filling";

const GET_INGREDIENTS = "GET_INGREDIENTS";
const GET_INGREDIENTS_SUCCES = "GET_INGREDIENTS_SUCCES";
const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
const SET_INGREDIENTS = "SET_INGREDIENTS";
const ADD_INGREDIENTS = "ADD_INGREDIENTS";
const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
const REMOVE_ALL_INGREDIENTS = "REMOVE_ALL_INGREDIENTS";
const REPLASE_INGREDIENT = "REPLASE_INGREDIENT";
const SET_ORDER = "SET_ORDER";
const SET_ORDER_SUCCES = "SET_ORDER_SUCCES";
const SET_ORDER_FAILED = "SET_ORDER_SUCCES";
const SET_ORDER_REMOVE = "SET_ORDER_REMOVE";
const RESET = "RESET";

export {
  API_URL,
  BUN,
  SAUCE,
  FILLING,
  GET_INGREDIENTS,
  GET_INGREDIENTS_SUCCES,
  GET_INGREDIENTS_FAILED,
  SET_INGREDIENTS,
  SET_ORDER_SUCCES,
  SET_ORDER_FAILED,
  SET_ORDER_REMOVE,
  ADD_INGREDIENTS,
  REMOVE_INGREDIENTS,
  REMOVE_ALL_INGREDIENTS,
  REPLASE_INGREDIENT,
  SET_ORDER,
  RESET,
};
